name: 2. Deploy Microservice
on: workflow_dispatch

env:
  # 👇 CONFIGURAR EN CADA REPO
  SVC_NAME: "ms-users"
  PORT: "8001"
  IMAGE: "aceofglass14/ms-users:latest"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. SSH Remoto para desplegar
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}  # <--- IP DEL SERVIDOR QUE CREASTE EN ESTA CUENTA
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}    # <--- EL CONTENIDO DEL PEM
          script: |
            # Login Docker
            echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
            
            # Limpiar anterior
            docker stop ${{ env.SVC_NAME }} || true
            docker rm ${{ env.SVC_NAME }} || true
            docker pull ${{ env.IMAGE }}
            
            # Correr nuevo (CONECTANDO A LA CUENTA CENTRAL #6)
            docker run -d \
              --name ${{ env.SVC_NAME }} \
              --restart always \
              -p ${{ env.PORT }}:${{ env.PORT }} \
              -e PORT=${{ env.PORT }} \
              -e RABBITMQ_HOST="${{ secrets.INFRA_IP }}" \
              -e POSTGRES_URL="postgresql://admin:admin123@${{ secrets.INFRA_IP }}:5432/appdb" \
              -e MONGO_URL="mongodb://${{ secrets.INFRA_IP }}:27017" \
              ${{ env.IMAGE }}