name: Destroy Infrastructure

# Se activa cuando se hace un push a la rama main (o la que decidas)
on:
  push:
    branches:
      - main  # O la rama en la que quieras que se ejecute (ej. "master")

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Paso para hacer un plan de destrucción (opcional, pero recomendable)
      - name: Terraform Plan (Destruction)
        run: |
          cd terraform
          terraform init
          terraform plan -destroy -out=tfplan

      # Paso para destruir la infraestructura
      - name: Terraform Destroy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          cd terraform
          terraform destroy -auto-approve
