name: Create Infrastructure
on:
  push:
    branches:
      - main  # Se ejecuta solo cuando haya un push en la rama main

env:
  # Nombres ÚNICOS para tu Backend (cámbialos en cada repo o usa sufijos)
  BUCKET: "tf-state-ms-users-exam-2026"
  TABLE: "tf-locks-ms-users-exam"

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # 1️⃣ PASO CRÍTICO: Crear Backend si no existe
      - name: Initialize Backend (S3 + Dynamo)
        run: |
          chmod +x scripts/init_backend.sh
          ./scripts/init_backend.sh ${{ env.BUCKET }} ${{ env.TABLE }}

      # 2️⃣ Terraform Init & Apply
      - name: Terraform Apply
        run: |
          cd terraform
          
          # Inicializar pasando la config del backend dinámicamente
          terraform init \
            -backend-config="bucket=${{ env.BUCKET }}" \
            -backend-config="dynamodb_table=${{ env.TABLE }}" \
            -backend-config="region=us-east-1"
            
          terraform apply -auto-approve

      - name: Upload Key Pair
        uses: actions/upload-artifact@v4
        with:
          name: ssh-key
          path: terraform/*.pem
