name: 1. Deploy Infrastructure
on: workflow_dispatch

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Apply
        env:
          # GitHub inyecta las credenciales de LA CUENTA que configuraste en este repo
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve

      - name: Guardar KeyPair
        uses: actions/upload-artifact@v4
        with:
          name: ssh-key
          path: terraform/*.pem